- hosts: all
  become: true

  tasks:
    - name: Update system packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install required tools
      ansible.builtin.yum:
        name:
          - wget
          - curl
          - vim
          - gnupg2
        state: latest

    - name: Install MariaDB server
      ansible.builtin.yum:
        name:
          - mariadb
          - mariadb-server
        state: latest

    - name: Start and enable MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Create Zabbix database and user
      ansible.builtin.mysql_db:
        name: zabbix
        state: present
        collation: utf8mb4_bin
        encoding: utf8mb4

    - name: Create Zabbix user
      ansible.builtin.mysql_user:
        name: zabbix
        password: zabbix_password
        host: localhost
        priv: "zabbix.*:ALL"
        state: present

    - name: Set global MySQL variable for function creators
      ansible.builtin.mysql_variables:
        name: log_bin_trust_function_creators
        value: 1

    - name: Add Zabbix repository
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/7.0/rhel/9/x86_64/zabbix-release-7.0-1.el9.noarch.rpm
        dest: /tmp/zabbix-release.rpm

    - name: Install Zabbix repository
      ansible.builtin.yum:
        name: /tmp/zabbix-release.rpm
        state: present

    - name: Install Zabbix server, frontend, and agent
      ansible.builtin.yum:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-web-apache-mysql
          - zabbix-sql-scripts
          - zabbix-agent2
        state: latest

    - name: Import Zabbix database schema
      ansible.builtin.command:
        cmd: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -pzabbix_password zabbix
      args:
        warn: false

    - name: Configure Zabbix server password
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: 'DBPassword=zabbix_password'

    - name: Start and enable Zabbix services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - zabbix-server
        - zabbix-agent2
        - httpd

    - name: Configure PHP for Zabbix frontend
      ansible.builtin.lineinfile:
        path: /etc/php.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^max_execution_time = .*', line: 'max_execution_time = 300' }
        - { regexp: '^memory_limit = .*', line: 'memory_limit = 128M' }
        - { regexp: '^post_max_size = .*', line: 'post_max_size = 16M' }
        - { regexp: '^upload_max_filesize = .*', line: 'upload_max_filesize = 2M' }
        - { regexp: '^;date.timezone =.*', line: 'date.timezone = Europe/Prague' }

    - name: Restart Apache service
      ansible.builtin.service:
        name: httpd
        state: restarted
