---
- name: Install and configure Zabbix server
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    zabbix_version: "7.0"
    zabbix_db_user: "zabbix_user"
    zabbix_db_password: "zabbix_password"
    zabbix_db_name: "zabbix"
    php_timezone: "Europe/Prague"

  tasks:
    - name: Update all system packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install required tools and dependencies
      ansible.builtin.dnf:
        name:
          - wget
          - curl
          - vim
          - gnupg2
          - mariadb
          - mariadb-server
          - httpd
          - php
          - php-mysqlnd
          - php-gd
          - php-xml
          - php-bcmath
          - php-mbstring
          - policycoreutils-python-utils
        state: present

    - name: Start and enable MariaDB
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: true

    - name: Configure MariaDB for Zabbix
      ansible.builtin.mysql_db:
        login_user: root
        name: "{{ zabbix_db_name }}"
        state: present
        encoding: utf8mb4
        collation: utf8mb4_bin

    - name: Create Zabbix database user
      ansible.builtin.mysql_user:
        login_user: root
        name: "{{ zabbix_db_user }}"
        password: "{{ zabbix_db_password }}"
        priv: "{{ zabbix_db_name }}.*:ALL"
        state: present

    - name: Add Zabbix repository
      ansible.builtin.shell: |
        rpm -Uvh https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/9/x86_64/zabbix-release-{{ zabbix_version }}-1.el9.noarch.rpm
        dnf clean all
      args:
        executable: /bin/bash

    - name: Install Zabbix server, frontend, and agent
      ansible.builtin.dnf:
        name:
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-web-apache-mysql
          - zabbix-sql-scripts
          - zabbix-agent2
        state: present

    - name: Import Zabbix database schema
      ansible.builtin.shell: |
        zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -u{{ zabbix_db_user }} -p{{ zabbix_db_password }} {{ zabbix_db_name }}
      args:
        executable: /bin/bash

    - name: Configure Zabbix server database password
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: "DBPassword={{ zabbix_db_password }}"

    - name: Configure PHP for Zabbix frontend
      ansible.builtin.lineinfile:
        path: /etc/php.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^max_execution_time = .*', line: 'max_execution_time = 300' }
        - { regexp: '^memory_limit = .*', line: 'memory_limit = 128M' }
        - { regexp: '^post_max_size = .*', line: 'post_max_size = 16M' }
        - { regexp: '^upload_max_filesize = .*', line: 'upload_max_filesize = 2M' }
        - { regexp: '^;date.timezone =.*', line: 'date.timezone = {{ php_timezone }}' }

    - name: Set SELinux permissions for Zabbix
      ansible.builtin.command: |
        setsebool -P httpd_can_connect_zabbix 1
        setsebool -P httpd_can_network_connect_db 1
      args:
        executable: /bin/bash

    - name: Start and enable Zabbix services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - zabbix-server
        - zabbix-agent2
        - httpd

    - name: Display final instructions
      ansible.builtin.debug:
        msg: |
          Zabbix setup is complete. Access the web interface at http://<your-server-ip>/zabbix
          Use the following credentials:
          Username: Admin
          Password: zabbix
