IMAGE_NAME = "bento/fedora-latest" # Fedora Latest

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "fedora" do |fedora|
    fedora.vm.box = IMAGE_NAME
    fedora.vm.network "forwarded_port", guest: 22, host: 2205, host_ip: "127.0.0.1"
    fedora.vm.network "forwarded_port", guest: 80, host: 8085, host_ip: "127.0.0.1"
    fedora.vm.hostname = "fedora"

    # Provisioning script
    fedora.vm.provision "shell", path: "provision.sh"

    # Copying SSH public key
    fedora.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/.ssh/me.pub"
    fedora.vm.provision "shell", inline: <<-SHELL
      mkdir -p /home/vagrant/.ssh
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant /home/vagrant/.ssh
    SHELL
  end
end